# Generated by Django 5.2.15 on 2026-06-25 05:38

import confronti.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confronti', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerArchiveFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=160, verbose_name='Nome cliente')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email cliente')),
                ('customer_phone', models.CharField(blank=True, max_length=40, verbose_name='Telefono cliente')),
                ('folder_name', models.CharField(editable=False, max_length=180, unique=True, verbose_name='Cartella archivio')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creata il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornata il')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_folders_created', to=settings.AUTH_USER_MODEL, verbose_name='Creata da')),
            ],
            options={
                'verbose_name': 'Cartella archivio cliente',
                'verbose_name_plural': 'Cartelle archivio clienti',
                'ordering': ('-updated_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ComparisonReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=180, verbose_name='Titolo report')),
                ('commodity', models.CharField(blank=True, max_length=12, verbose_name='Fornitura')),
                ('providers_label', models.CharField(blank=True, max_length=120, verbose_name='Fornitori confronto')),
                ('bill_period_label', models.CharField(blank=True, max_length=120, verbose_name='Periodo bolletta')),
                ('comparison_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Confronto eseguito il')),
                ('report_file', models.FileField(max_length=255, upload_to=confronti.models.archive_report_upload_to, verbose_name='File report')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Nome file originale')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('comparison_data', models.JSONField(blank=True, default=dict, verbose_name='Dati confronto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comparison_reports_created', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='confronti.customerarchivefolder', verbose_name='Cartella cliente')),
            ],
            options={
                'verbose_name': 'Report confronto archiviato',
                'verbose_name_plural': 'Report confronti archiviati',
                'ordering': ('-comparison_datetime', '-created_at'),
            },
        ),
    ]
