# Generated by Django 5.2.15 on 2026-07-01 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confronti', '0002_customerarchivefolder_comparisonreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonreport',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='confronti.customerarchivefolder', verbose_name='Cartella cliente'),
        ),
    ]
